<?php 
return [
    'sepay_apikey' => env('sepay_apikey', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST'),
    'ten_nganhang' => env('ten_nganhang', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST')
    ,
    'webhook_url' => env('webhook_url', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST')
    ,
    'so_taikhoan' => env('so_taikhoan', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST')
    ,
    'chu_taikhoan' => env('chu_taikhoan', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST')
    ,
    'tiento_mahoa' => env('tiento_mahoa', 'QAGQKXNZBPOIZDHBU53Q4RVOYRJF2RFWPX0EUZEIDZLPKC0869IVDWXBM7NRXFST')
];